### ISSUE TITLE
integrating wasm-bindgen

### ISSUE THREAD

**Issue by ashleygwilliams** [ashleygwilliams/wasm-pack#13]
there are several steps to using `wasm-bindgen` that i'd like to discuss here:

1. `rustup target add wasm32-unknown-unknown`
2. add `wasm-bindgen` as a dep to `Cargo.toml`:
   
   ```toml
    [lib]
    crate-type = ["cdylib"]

    [dependencies]
    wasm-bindgen = { git = 'https://github.com/alexcrichton/wasm-bindgen' }
   ```

3. add the following code to your `src/lib.rs`:

   ```rust
   #![feature(proc_macro)]

   extern crate wasm_bindgen;

   use wasm_bindgen::prelude::*;

   #[wasm_bindgen]
   extern {
       fn alert(s: &str);
   }
   ```

4. add this annotation to each publicly exported function:

   ```rust
   #[wasm_bindgen]
   #[no_mangle]
   ```

5.  `cargo build --release --target wasm32-unknown-unknown`
6.  `cargo install --git https://github.com/alexcrichton/wasm-bindgen` (this seems redundant with 2??? https://github.com/alexcrichton/wasm-bindgen/issues/44)
7. `wasm-bindgen target/wasm32-unknown-unknown/release/<name of lib>.wasm \
  --out-dir .` (ergonomics ask: https://github.com/alexcrichton/wasm-bindgen/issues/45)

i can see clear ways to integrate 1, 2, 5, 6, 7. 3 and 4 will need to be done manually by the user. @alexcrichton do you have any thoughts on this?
